Update deployment.yaml

diff --git a/whisperwebui/templates/deployment.yaml b/whisperwebui/templates/deployment.yaml
--- a/whisperwebui/templates/deployment.yaml
+++ b/whisperwebui/templates/deployment.yaml
@@ -3,44 +3,112 @@
 apiVersion: apps/v1
 kind: Deployment
 metadata:
-  name: whisperwebuishare
+  name: whisperwebui
   namespace: {{ .Release.Namespace }}
   labels:
-    app: whisperwebuishare
+    app: whisperwebui
+  annotations:
+    applications.app.bytetrade.io/gpu-inject: "true"
 spec:
   replicas: 1
   selector:
     matchLabels:
-      app: whisperwebuishare
+      app: whisperwebui
   strategy:
     type: Recreate
   template:
     metadata:
       labels:
-        app: whisperwebuishare
+        app: whisperwebui
     spec:
       securityContext:
         runAsUser: 0
       initContainers:
-        - name: copy-configs
+        - name: copy-configs-download-models
           image: jhj0517/whisper-webui:v1.0.4
+          envFrom:
+            - configMapRef:
+                name: whisperwebui-config
           command:
             - sh
             - '-c'
             - |
               mkdir -p /tmp/configs;
               cp -rupv /Whisper-WebUI/configs/. /tmp/configs/;
+              
+              if echo "${CDN_HOST}" | grep -q "joinolares.cn"; then
+                echo "use China mirrors..."
+                sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
+              fi
+              
+              DOWNLOAD_URL="${CDN_HOST}/whisperwebui_models.tar.zst"
+              MODEL_ROOT="/tmp/whisperwebui/models"
+              DOWNLOAD_TMP="${MODEL_ROOT}/download/models.tar.zst"
+              WORKDIR="/tmp/workspace"
+              MODEL_MARKER="${MODEL_ROOT}/.success_marker"
+
+              rm -rf "${WORKDIR}"
+              mkdir -p "${MODEL_ROOT}" "${WORKDIR}"
+
+              if [ -f "${MODEL_MARKER}" ]; then
+                echo "Directory ${MODEL_ROOT} is not empty, skip initialization."
+                exit 0
+              fi
+              apt clean && apt update && apt install -y rsync aria2 zstd pv;
+
+              echo "Downloading model from $DOWNLOAD_URL..."
+              aria2c \
+                --continue=true \
+                --max-concurrent-downloads=4 \
+                --split=4 \
+                --max-connection-per-server=4 \
+                --min-split-size=50M \
+                --timeout=20 \
+                --max-tries=0 \
+                --retry-wait=10 \
+                --check-certificate=false \
+                --allow-overwrite=true \
+                --file-allocation=prealloc \
+                --disk-cache=64M \
+                --summary-interval=0 \
+                --quiet=false \
+                --enable-color=false \
+                --dir="$(dirname "$DOWNLOAD_TMP")" \
+                --out="$(basename "$DOWNLOAD_TMP")" \
+                "$DOWNLOAD_URL" || { echo "Download failed!"; exit 1; }
+
+              echo "[$(date +%H:%M:%S)] Extracting files..."
+              pv "${DOWNLOAD_TMP}" | tar -I 'zstd -T0' -C "${WORKDIR}" --strip-components=1 -xf - || {
+                echo "Extraction failed!"
+                rm -f "${DOWNLOAD_TMP}"
+                exit 1
+              }
+
+              ls -ld "${WORKDIR}"
+
+              echo "[$(date +%H:%M:%S)] Syncing files..."
+              rsync -av --ignore-existing "${WORKDIR}/" "${MODEL_ROOT}/" || {
+                echo "Sync failed!"
+                exit 1
+              }
+
+              touch "${MODEL_MARKER}"
+
+              rm -rf "${WORKDIR}" "${DOWNLOAD_TMP}"
+              echo "[$(date +%H:%M:%S)] Initialization completed!"
               exit 0
           volumeMounts:
             - name: configs
               mountPath: /tmp/configs
+            - name: models
+              mountPath: /tmp/whisperwebui/models
           terminationMessagePath: /dev/termination-log
           terminationMessagePolicy: File
           imagePullPolicy: IfNotPresent
           securityContext:
             runAsUser: 0
       containers:
-        - name: whisperwebuishare
+        - name: whisperwebui
           image: jhj0517/whisper-webui:v1.0.4
           envFrom:
             - configMapRef:
@@ -96,7 +164,7 @@ metadata:
   namespace: {{ .Release.Namespace }}
 spec:
   selector:
-    app: whisperwebuishare
+    app: whisperwebui
   ports:
     - name: api
       port: 7860
